### ISSUE TITLE
Image asset "incorrect" for waypoint questions

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-student-app#10]
This looks odd ... can we have a red icon for incorrect waypoints?

<img width="432" alt="captura de pantalla 2016-08-19 a las 1 38 15 pm" src="https://cloud.githubusercontent.com/assets/4930129/17818616/63b92742-6612-11e6-824a-ca524e88baa3.png">

**Comment by luwen-huang** [comment]
fixed
