### ISSUE TITLE
how to know which Item an Answer belongs to?

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#18]
is there anything in the returned worked solution object that will tell me which Item it belongs to? I'm examining the response and I can't find anything...
![screen shot 2016-08-28 at 2 55 44 pm](https://cloud.githubusercontent.com/assets/2822290/18033914/b51c4686-6d2f-11e6-9109-13f9921d2d49.png)

**Comment by cjshawMIT** [comment]
Not in the object itself — you should know from the URL that you send?
