### ISSUE TITLE
returning the AnswerResponse schema should follow the same schema for QuestionItem

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#21]
the QuestionItem.response schema is:

{...
  isCorrect: Boolean
 ...
}

but the AnswerResponse (what you get after submitting a choice) is:
{...
 correct: Boolean
}

let's change that field to match so that "correct" --> isCorrect.

**Comment by cjshawMIT** [comment]
Just pushed this to qbank-dev. I expect you will update the app side?

**Comment by luwen-huang** [comment]
yes, thanks. actually i only noticed this because the app side was assuming
this and breaking.
