### ISSUE TITLE
Extra "bottom" level question before moving up?

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-student-app#24]
Luwen reported: when you get the bottom level question wrong several times, then get it right, Luwen saw it give an extra bottom-level question before scaffolding back up ... but only once?

Need to test.

**Comment by luwen-huang** [comment]
Definitely something buggy at the bottom of the tree. Try to assert these test cases:

* get a bottom-level question wrong a few times, e.g. 4 times
* then get it right ==> doesn't return the next question up like it's supposed to
---
* get a bottom-level question 2 times
* then get it right ==> this returns the same bottom-level question
* get the question right ==> returns the next question up

**Comment by cjshawMIT** [comment]
I’ll write a test for this … but I wonder if it’s related to the Q(qbankFetch) issue, making redundant calls…?

**Comment by cjshawMIT** [comment]
I believe this has been fixed and deployed to dev
