### ISSUE TITLE
create UI visual at end of scaffold

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#33]
app should auto scroll back up, ding, turn yellow

**Comment by luwen-huang** [comment]
is it completely derivable from the section's questions data? or do we need the response object to tell us if there's a next question?

**Comment by luwen-huang** [comment]
how i'm doing it now, that relies on the response object: 

https://github.com/wombats-writing-code/fbw-student-app/blob/master/common/stores/AssessmentTakenQuestion.js#L133

**Comment by cjshawMIT** [comment]
I don’t think we need a response object. The “get next question on submit” and “get all questions” uses the same logic to update the questions list / find the “next” question, so I believe when we call “get all questions”, we should be able to build a selector to figure out if a route has been finished successfully or not. I will try to build out an example.

**Comment by cjshawMIT** [comment]
Pushed a commit that includes this. Please test and provide feedback...I think we can close the issue.

**Comment by luwen-huang** [comment]
mmm, i think there remains a small bug -- the target shows yellow, but the question was in fact answered correctly.

![simulator screen shot oct 9 2016 9 53 07 am](https://cloud.githubusercontent.com/assets/2822290/19220912/6014c864-8e06-11e6-8edb-f0f0b6196443.png)
