### ISSUE TITLE
when an Item is being fetched, the Outcome should be fetched in parallel too

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#4]
Because whenever we need an Item, we'll always need its tagged Outcome. we could:

1) make the getNextAssessmentTakenQuestion method execute 2 requests in series, first to get the Item, then to get the Outcomes. I really don't like this because the call is slow enough as is.

2) make qbank return the whole Outcome object instead of just the ID for every Item. maybe we can have a query parameter like ?full_outcome=true or something. I like this better.

**Comment by cjshawMIT** [comment]
Why not do what the instructor app does, and fetch all the outcomes at the start, then keep them around as a map? Making qbank return the full outcome object is essentially the same as doing two calls, because qbank has to make the call to handcar ...

**Comment by luwen-huang** [comment]
Ah. that's a better idea. yes, let's do that then.
