### ISSUE TITLE
Scaffolding breaks when outcomes are changed for distractors

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#45]
1) Go to the Target Use the LIFO method to calculate ending merchandise inventory

2) Select $1,400 [tagged with a **new** outcome Compare FIFO and LIFO inventory costing calculations]

3) The cue says "Let's try to Use the LIFO method to calculate ending merchandise inventory again". that's not right.

@dnshah to add more info -- what was the old outcome?

**Comment by dnshah** [comment]
Old outcome for that distractor was "Distinguish between the LIFO and FIFO methods".

**Comment by cjshawMIT** [comment]
This is because I sent the wrong credentials to @luwen-huang , so 1.3 of the student app is talking to mc3-dev for handcar. Sent Luwen updated credentials and also updated the data store on mc3-dev to match prod.
