### ISSUE TITLE
webview for solutions getting truncated

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#49]
example, Apply the change of base formula, 2nd target. Choose 4.174, then log z x / log z y. That's a wrong answer and then see solution -- that's getting truncated.

**Comment by cjshawMIT** [comment]
I cannot replicate? I've verified that the solution in the authoring tool only has that one step...

<img width="880" alt="captura de pantalla 2016-10-14 a las 11 17 23 am" src="https://cloud.githubusercontent.com/assets/4930129/19392681/d75d1410-91ff-11e6-90db-8694c2a26311.png">

**Comment by luwen-huang** [comment]
really? @dnshah then shouldn't that line be changed? because that implies
there should be other steps...

**Comment by dnshah** [comment]
Yes, that is confusing. Readers will expect there to be more if "Step 1" is explicitly called out. We'll modify 1-step solutions so that they do not have the solution step headers.

**Comment by luwen-huang** [comment]
closing on tech end
