### ISSUE TITLE
Request: two new states in target carousel

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-student-app#5]
For UX, can we have two new states in the target carousel, something like: IN_PROGRESS_FAILED and SELECTED_COMPLETE? Right now it's a bit confusing because if you got a question wrong but you're working through the waypoints, the target question icon is yellow background, but gray target. If you move off of it, it turns into a red target. Can we have a IN_PROGRESS_FAILED that is yellow background, red target?

Similarly, if you go back to a target you got right, can we have a SELECTED_COMPLETE that is yellow background, green target?

**Comment by luwen-huang** [comment]
Ok, so I've tweaked the definition of things a little. We no longer have an in-progress -- we have instead a currentTarget (what you're seeing currently) and the lastActiveTarget ==> the opacity changes depending on whether or not it's currently active. 

Then it's just a matter of whether the Target has been COMPLETE'd or FAIL'ed. If this resolves things, mark as close?

**Comment by cjshawMIT** [comment]
Okay, let me take a look, probably later this week. Thanks!
