### ISSUE TITLE
Styling warnings in ReactNative?

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-student-app#8]
Should we ignore these?

![captura de pantalla 2016-08-18 a las 4 41 18 pm](https://cloud.githubusercontent.com/assets/4930129/17790012/b57c9d58-6562-11e6-8b00-d8b9018b4ece.png)

**Comment by luwen-huang** [comment]
um. can't replicate. is there a specific screen where you start to see this or just everywhere upon first load?

**Comment by cjshawMIT** [comment]
Huh, basically everywhere ... I removed everything in `node_modules` and re-`npm install`, but I still get the warnings. I've squelched the yellow box warnings in the code, but they still show up in debugger ....

<img width="2304" alt="captura de pantalla 2016-08-22 a las 11 41 58 am 2" src="https://cloud.githubusercontent.com/assets/4930129/17861078/a7fca88c-685d-11e6-84f5-2310f5eb8113.png">

**Comment by luwen-huang** [comment]
could be a mismatch on our react installations? i still can't reproduce. http://stackoverflow.com/questions/38690502/manually-calling-a-react-proptypes-validation-react-native-0-30-0

in any case, let's bump this fix and version upgrade to a later date after october.
